version: '3.1'
services:
  app:
    image: herpiko/kibotin-app:latest
  api:
    image: herpiko/kibotin-api:latest
    volumes:
    - ./outputs:/dist/outputs
  proxy:
    image: citradigital/proxy
    restart: always
    ports:
    - 443:443
    environment:
    - DEBUG=1
    volumes:
    - ./certs/fullchain.pem:/fullchain.pem
    - ./certs/privkey.pem:/privkey.pem
    - ./services.yaml:/services.yaml:ro

